# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 096e1848d1c6c7cec17fddb1f0a0d7a5d19e37d7f75ade86b49ccf92603e15151086c734a314641fe5c0b5c26b8fa285ed68555b67f1d8a93c16161c37b5893c

test:
  secret_key_base: 3e6b026611d494b10d0e1632cd06b2407252edd2a59d29a7784be148725788d9310053923928233352d8bd76e32553af4b36c89936bb4caaa6378ffa97b2cde2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
